version: "3.5"

# VOLUMES: Defines storage locations managed by Docker, bound to specific host paths
volumes:
  mariadb_data: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gsims/data/mariadb' 
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/gsims/data/wordpress'

# NETWORKS: Defines virtual networks for container communication
networks: 
  inception: 

# SERVICES: Defines each containerized application
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    volumes: 
      - mariadb_data:/var/lib/mysql  
    env_file:
      - .env
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks: 
      - inception
    restart: on-failure
    
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443" # HTTPS Port
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf  # NGINX config (bind mount)
      - wordpress_data:/var/www/html  
    networks:
      - inception
    restart: always
    
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/.
    volumes:
      - wordpress_data:/var/www/html  
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
    networks: 
      - inception
    restart: always

